# fly.toml file generated for toy-bank-bot on 2022-08-27T22:51:16+06:00

app = "subtitle-downloader-bot"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "heroku/buildpacks:latest"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

